<!DOCTYPE html>
<html>
<head>
    <title>Proof of Registration - Honey Bee Culinary Institute</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #1f2937; line-height: 1.55; }
        .header { border-bottom: 3px solid #d97706; padding-bottom: 16px; margin-bottom: 28px; }
        .brand { font-size: 22px; font-weight: 700; color: #92400e; }
        .muted { color: #6b7280; font-size: 12px; }
        .box { border: 1px solid #e5e7eb; padding: 14px; margin: 18px 0; background: #fefce8; }
        .label { font-weight: 700; }
        .signature { margin-top: 36px; }
        .footer { margin-top: 40px; font-size: 11px; color: #6b7280; text-align: center; border-top: 1px solid #e5e7eb; padding-top: 16px; }
        .status-box { display: inline-block; background: #dcfce7; color: #166534; padding: 4px 12px; border-radius: 4px; font-weight: 700; }
    </style>
</head>
<body>
    <div class="header">
        <div class="brand">Honey Bee Culinary Institute</div>
        <div class="muted">Proof of Registration | Reference HBCI-REG-{{ str_pad($application->id, 5, '0', STR_PAD_LEFT) }}</div>
    </div>

    <p>This is to certify that the student listed below has completed registration at Honey Bee Culinary Institute.</p>

    <div class="box">
        <p><span class="label">Student Name:</span> {{ $student->name }}</p>
        @if(! empty($student->student_number))
            <p><span class="label">Student Number:</span> {{ $student->student_number }}</p>
        @endif
        @if(! empty($student->email))
            <p><span class="label">Email:</span> {{ $student->email }}</p>
        @endif
        <p><span class="label">Programme:</span> {{ $application->programme?->name ?? 'N/A' }}</p>
        @if($application->variant)
            <p><span class="label">Study Option:</span> {{ $application->variant->label }}</p>
        @endif
        <p><span class="label">Registration Status:</span> <span class="status-box">Completed</span></p>
        <p><span class="label">Registration Date:</span> {{ $application->registered_at?->format('d F Y') ?? 'N/A' }}</p>
    </div>

    <div class="box">
        <p><span class="label">Enrolled Modules:</span></p>
        @if($modules && $modules->count() > 0)
            <ul style="margin: 8px 0 0 20px; padding: 0;">
                @foreach($modules as $module)
                    <li>{{ $module->name }} ({{ $module->code }})</li>
                @endforeach
            </ul>
        @else
            <p>No modules enrolled yet.</p>
        @endif
    </div>

    <p>
        This document serves as official proof of registration. Please present this document when requested by the institute.
    </p>

    <div class="signature">
        <p>Sincerely,</p>
        <p><strong>The Admissions Team</strong><br>Honey Bee Culinary Institute</p>
        <p style="font-size: 12px; color: #6b7280; margin-top: 8px;">
            Generated on: {{ now()->format('d F Y H:i:s') }}
        </p>
    </div>

    <div class="footer">
        <p>Honey Bee Culinary Institute | The Hive Management System</p>
        <p>This is an official document generated by the institute's management system.</p>
    </div>
</body>
</html>